### ISSUE TITLE
Error: Non-whitespace before first tag.

### ISSUE THREAD

**Issue by CinKon** [tomgrooffer/icons-loader#2]
Hi,

for every svg-icon i want to use, i get the following error log:

```
Listening at http://localhost:8080

webpack: wait until bundle finished: /__webpack_hmr
/src/node_modules/webpack-dev-middleware/middleware.js

:106
                        if(err) throw err;
                                ^

Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: m
    at error (/src/node_modules/sax/lib/sax.js:667:10)
    at strictFail (/src/node_modules/sax/lib/sax.js:69
3:7)
    at beginWhiteSpace (/src/node_modules/sax/lib/sax.
js:967:7)
    at Object.write (/src/node_modules/sax/lib/sax.js:
1019:11)
    at SAXStream.write (/src/node_modules/sax/lib/sax.
js:239:18)
    at PassThrough.ondata (/src/node_modules/readable-
```

After some research, this seems to be a problem with UTF8-Encoded SVGs. I'm not that into node-Modules, so could you provide a fix for this?
Here is a possible [solution](http://www.multiasking.com/blog/xml2js-sax-js-non-whitespace-before-first-tag/)

I use icons from [iconmonstr.com](http://iconmonstr.com), but even self-generated icons with Sketch or Illustrator doesn't work.

Thanks!

**Comment by CinKon** [comment]
Sorry, seems to be a known issue with saxjs :)

**Comment by pulkitjalan** [comment]
@CinKon did u ever find a workaround or a fix?

**Comment by CinKon** [comment]
Can't remember, sorry
